# Generated by Django 5.2 on 2025-05-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice', models.CharField(max_length=15, unique=True)),
                ('name_respo', models.CharField(max_length=100)),
                ('name_ent', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('products', models.ManyToManyField(blank=True, to='products.product')),
            ],
        ),
    ]
