# Generated by Django 5.2.1 on 2025-06-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internalOrders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='internalorder',
            table='internalorders_internalorder',
        ),
    ]
