# Generated by Django 5.2.1 on 2025-06-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internalOrders', '0002_alter_internalorder_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='externalorders_orderitem',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='externalorders_payment',
        ),
    ]
