# Generated by Django 5.2.1 on 2025-06-04 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internalOrders', '0003_alter_orderitem_table_alter_payment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='internalorders_orderitem',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='internalorders_payment',
        ),
    ]
