# Generated by Django 5.2 on 2025-05-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ice',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ICE'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Téléphone'),
        ),
    ]
