# Generated by Django 5.2 on 2025-05-24 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPrivileges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_product', models.BooleanField(default=False)),
                ('edit_product', models.BooleanField(default=False)),
                ('delete_product', models.BooleanField(default=False)),
                ('add_order', models.BooleanField(default=False)),
                ('edit_order', models.BooleanField(default=False)),
                ('delete_order', models.BooleanField(default=False)),
                ('add_client', models.BooleanField(default=False)),
                ('edit_client', models.BooleanField(default=False)),
                ('delete_client', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privileges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
