# Generated by Django 5.2.1 on 2025-06-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprivileges',
            name='add_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprivileges',
            name='delete_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprivileges',
            name='edit_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
