# Generated by Django 5.2.1 on 2025-06-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_sellerprivileges_add_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprivileges',
            name='add_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprivileges',
            name='delete_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprivileges',
            name='edit_category',
            field=models.BooleanField(default=False),
        ),
    ]
