# Generated by Django 5.2 on 2025-05-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('validity', models.CharField(max_length=100)),
                ('product_id', models.BigIntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('product_category', models.CharField(max_length=100)),
                ('images', models.CharField(blank=True, max_length=255, null=True)),
                ('normal_price', models.FloatField()),
                ('promotion_price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
