# Generated by Django 5.2 on 2025-05-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='product_category',
            field=models.IntegerField(),
        ),
    ]
