# Generated by Django 5.2.1 on 2025-06-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('externalOrders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='externalorder',
            table='externalorders_externalorder',
        ),
    ]
