# Generated by Django 5.2.1 on 2025-06-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('externalOrders', '0002_alter_externalorder_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='externalorders_orderitem',
        ),
    ]
