# Generated by Django 5.2 on 2025-05-26 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_number', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_address', models.TextField()),
                ('prepared_by', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True, null=True)),
                ('order_num', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.FloatField()),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery_notes.deliverynote')),
            ],
        ),
    ]
