# Generated by Django 5.2 on 2025-05-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactureClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=255)),
                ('order_num', models.CharField(max_length=100)),
                ('client_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('date', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_internal', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FactureFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=50)),
                ('order_num', models.CharField(max_length=100)),
                ('supplier_id', models.CharField(max_length=100)),
                ('supplier_name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('date', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
