# Generated by Django 5.2 on 2025-05-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturefournisseur',
            name='supplier_id',
            field=models.IntegerField(),
        ),
    ]
